name: CI + CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI – Docker Build Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (CI check)
        run: docker build -t ci3-app-test .

  deploy:
    name: CD – Deploy to EC2
    needs: ci
    runs-on: self-hosted
    environment: Deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
          cd /home/ubuntu/ci3-app
          git pull origin main
          docker compose up -d --build

